/* eslint-disable react-refresh/only-export-components */
import { createContext, useContext, useEffect, useMemo, useState } from "react";

type Language = "en" | "hi";

type LanguageContextValue = {
  language: Language;
  setLanguage: (language: Language) => void;
  toggleLanguage: () => void;
  t: (key: string, fallback?: string) => string;
};

const STORAGE_KEY = "adruva-language";

const translations: Record<Language, Record<string, string>> = {
  en: {
    "nav.services": "Services",
    "nav.demo": "Demo",
    "nav.pricing": "Pricing",
    "nav.why": "Why Adruva Resto",
    "nav.contact": "Contact",
    "nav.ownerLogin": "Owner Login",
    "nav.freeConsultation": "Free Consultation",
    "lang.label.en": "EN",
    "lang.label.hi": "हिं",
    "hero.badge": "Your Digital Partner for Restaurants",
    "hero.titlePrefix": "Grow Your Restaurant",
    "hero.titleHighlight": "Online",
    "hero.description":
      "Get a modern restaurant website and attract more customers with Adruva Resto. From digital menus to online ordering, we handle everything.",
    "hero.primaryCta": "Get My Restaurant Website",
    "hero.secondaryCta": "View Demo",
    "hero.stat.restaurants": "Restaurants Served",
    "hero.stat.orders": "More Online Orders",
    "hero.stat.price": "Starting Price",
    "audit.badge": "Free Website Audit",
    "audit.titlePrefix": "Your Restaurant Website",
    "audit.titleHighlight": "Score",
    "audit.subtitle": "Enter your website URL and get an instant score with actionable improvements",
    "audit.placeholder": "e.g. www.myrestaurant.com",
    "audit.analyze": "Analyze My Website",
    "audit.analyzing": "Analyzing...",
    "audit.scanning": "Scanning in progress",
    "audit.ctaTitle": "Want to fix these issues?",
    "audit.ctaDescription":
      "Our team will optimize your restaurant website for better rankings, more customers, and more orders.",
    "audit.ctaButton": "Fix My Website with Adruva Resto",
    "audit.grade.great": "Great",
    "audit.grade.good": "Good",
    "audit.grade.needsWork": "Needs Work",
    "audit.grade.poor": "Poor",
    "audit.step.fetch": "Fetching website...",
    "audit.step.mobile": "Checking mobile optimization...",
    "audit.step.speed": "Measuring page speed...",
    "audit.step.seo": "Analyzing SEO...",
    "audit.step.menu": "Scanning for online menu...",
    "audit.step.visibility": "Checking Google visibility...",
    "audit.step.report": "Generating report...",
    "audit.category.mobile": "Mobile Optimization",
    "audit.category.speed": "Page Speed",
    "audit.category.seo": "SEO",
    "audit.category.menu": "Online Menu",
    "audit.category.visibility": "Google Visibility",
    "audit.issue.single": "issue",
    "audit.issue.plural": "issues",
    "cta.titlePrefix": "Get Your Restaurant",
    "cta.titleHighlight": "Online Today",
    "cta.description":
      "Fill the form and get a free consultation. We'll analyze your restaurant's digital needs and suggest the best plan for you.",
    "cta.point.free": "Free consultation, no commitment",
    "cta.point.fast": "Website ready in 3-5 days",
    "cta.point.support": "Dedicated support manager",
    "cta.point.guarantee": "100% satisfaction guarantee",
    "cta.formTitle": "Get Free Consultation",
    "cta.formSubtitle": "Our team will call you within 24 hours",
    "cta.placeholder.restaurant": "Restaurant Name *",
    "cta.placeholder.owner": "Owner Name *",
    "cta.placeholder.phone": "Phone Number *",
    "cta.placeholder.city": "City",
    "cta.submit": "Get Free Consultation",
    "cta.submitting": "Submitting...",
    "cta.footer": "No cost. No commitment. Just a call.",
    "owner.login.title": "Owner Dashboard",
    "owner.login.welcome": "Welcome Back",
    "owner.login.create": "Create Account",
    "owner.login.fullName": "Full Name",
    "owner.login.email": "Email",
    "owner.login.password": "Password",
    "owner.login.wait": "Please wait...",
    "owner.login.signUp": "Sign Up",
    "owner.login.login": "Login",
    "owner.login.haveAccount": "Already have an account?",
    "owner.login.noAccount": "Don't have an account?",
    "owner.orders": "Orders",
    "owner.billing": "Billing",
    "owner.analytics": "Analytics",
    "owner.menu": "Menu",
    "owner.kitchen": "Kitchen",
    "owner.inventory": "Inventory",
    "owner.tables": "Tables & QR",
    "owner.rooms": "Rooms & QR",
    "owner.expenses": "Expenses",
    "owner.customers": "Customers",
    "owner.staff": "Staff",
    "owner.chain": "Chain",
    "owner.settings": "Settings",
    "owner.install": "Install App",
    "owner.support.whatsapp": "WhatsApp Support",
    "owner.logout": "Logout",
    "dashboard.title": "Orders",
    "dashboard.tab.active": "Active",
    "dashboard.tab.new": "New",
    "dashboard.tab.accepted": "Accepted",
    "dashboard.tab.preparing": "Preparing",
    "dashboard.tab.ready": "Ready",
    "dashboard.tab.all": "All",
    "dashboard.ordersUnavailable": "Orders are not available",
    "dashboard.ordersUnavailableHint": "Your account is not linked to a restaurant owner yet.",
    "dashboard.noOrders": "No orders found",
    "dashboard.noOrdersHint": "Orders appear here in real-time",
    "dashboard.table": "Table",
    "dashboard.justNow": "Just now",
    "dashboard.minutesAgo": "m ago",
    "dashboard.hoursAgo": "h",
    "dashboard.mark": "Mark",
    "dashboard.status.new": "new",
    "dashboard.status.accepted": "accepted",
    "dashboard.status.preparing": "preparing",
    "dashboard.status.ready": "ready",
    "dashboard.status.served": "served",
    "dashboard.status.cancelled": "cancelled",
    "expenses.title": "Expenses & Reports",
    "expenses.export": "Export CSV",
    "expenses.add": "Add Expense",
    "expenses.unavailable": "Expenses are not available",
    "expenses.unavailableHint": "Your account is not linked to a restaurant owner yet.",
    "expenses.revenue": "Revenue",
    "expenses.expenses": "Expenses",
    "expenses.netProfit": "Net Profit",
    "expenses.inventoryValue": "Inventory Value",
    "expenses.profitMargin": "Profit Margin",
    "expenses.all": "All Expenses",
    "expenses.none": "No expenses recorded this month",
    "expenses.noneHint": "Add expenses to track your costs",
    "expenses.edit": "Edit Expense",
    "expenses.addDialog": "Add Expense",
    "expenses.category": "Category",
    "expenses.amount": "Amount (INR)",
    "expenses.pickDate": "Pick date",
    "expenses.paymentMethod": "Payment Method",
    "expenses.notes": "Notes (optional)",
    "expenses.save": "Save Expense",
    "expenses.saved": "Expense saved",
    "expenses.deleted": "Expense deleted",
    "expenses.noData": "No data to export",
    "settings.title": "Restaurant Settings",
    "settings.restaurantInfo": "Restaurant Info",
    "settings.logo": "Logo",
    "settings.upload": "Upload",
    "settings.uploading": "Uploading...",
    "settings.change": "Change",
    "settings.restaurantName": "Restaurant Name",
    "settings.phone": "Phone Number",
    "settings.timing": "Timing",
    "settings.opensAt": "Opens At",
    "settings.closesAt": "Closes At",
    "settings.gstLocation": "GST & Location",
    "settings.gstNumber": "GST Number",
    "settings.gstPercentage": "GST Percentage (%)",
    "settings.address": "Address",
    "settings.autoDetect": "Auto-detect Location",
    "settings.detecting": "Detecting...",
    "settings.orderDiameter": "Order Diameter (GPS Verification)",
    "settings.orderDiameterHint": "Customers must be within this diameter zone to place orders from tables/rooms",
    "settings.payment": "Payment",
    "settings.upi": "UPI ID",
    "settings.save": "Save Settings",
    "settings.saving": "Saving...",
    "settings.logoUploaded": "Logo uploaded!",
    "settings.logoUploadFailed": "Logo upload failed",
    "settings.logoRemoved": "Logo removed",
    "settings.logoRemoveFailed": "Logo remove failed",
    "settings.savedSuccess": "Settings saved!",
    "settings.saveFailed": "Failed to save",
    "settings.gpsUnsupported": "GPS not supported on this device",
    "settings.locationDetected": "Location detected!",
    "settings.fetchAddressFailed": "Could not fetch address",
    "settings.locationDenied": "Location access denied",
    "settings.locationFailed": "Could not detect location",
    "customer.tableOccupied": "is occupied right now. Please contact staff or scan another table QR.",
  },
  hi: {
    "nav.services": "सेवाएं",
    "nav.demo": "डेमो",
    "nav.pricing": "प्राइसिंग",
    "nav.why": "क्यों Adruva Resto",
    "nav.contact": "संपर्क",
    "nav.ownerLogin": "ओनर लॉगिन",
    "nav.freeConsultation": "फ्री कंसल्टेशन",
    "lang.label.en": "EN",
    "lang.label.hi": "हिं",
    "hero.badge": "रेस्टोरेंट्स के लिए आपका डिजिटल पार्टनर",
    "hero.titlePrefix": "अपने रेस्टोरेंट को",
    "hero.titleHighlight": "ऑनलाइन बढ़ाएं",
    "hero.description":
      "Adruva Resto के साथ modern restaurant website पाएं और ज़्यादा customers जोड़ें. Digital menu से online ordering तक, सब हम संभालते हैं.",
    "hero.primaryCta": "मेरी रेस्टोरेंट वेबसाइट बनाएं",
    "hero.secondaryCta": "डेमो देखें",
    "hero.stat.restaurants": "रेस्टोरेंट्स सर्व किए",
    "hero.stat.orders": "ज़्यादा ऑनलाइन ऑर्डर्स",
    "hero.stat.price": "शुरुआती कीमत",
    "audit.badge": "फ्री वेबसाइट ऑडिट",
    "audit.titlePrefix": "आपकी रेस्टोरेंट वेबसाइट",
    "audit.titleHighlight": "स्कोर",
    "audit.subtitle": "अपनी वेबसाइट URL डालें और तुरंत actionable improvements के साथ score पाएं",
    "audit.placeholder": "जैसे www.myrestaurant.com",
    "audit.analyze": "मेरी वेबसाइट चेक करें",
    "audit.analyzing": "चेक हो रही है...",
    "audit.scanning": "स्कैन जारी है",
    "audit.ctaTitle": "इन issues को ठीक करना चाहते हैं?",
    "audit.ctaDescription":
      "हमारी team आपकी restaurant website को better rankings, ज़्यादा customers और ज़्यादा orders के लिए optimize करेगी.",
    "audit.ctaButton": "Adruva Resto के साथ वेबसाइट ठीक करें",
    "audit.grade.great": "बेहतरीन",
    "audit.grade.good": "अच्छा",
    "audit.grade.needsWork": "सुधार चाहिए",
    "audit.grade.poor": "कमज़ोर",
    "audit.step.fetch": "वेबसाइट ली जा रही है...",
    "audit.step.mobile": "मोबाइल ऑप्टिमाइजेशन चेक हो रहा है...",
    "audit.step.speed": "स्पीड मापी जा रही है...",
    "audit.step.seo": "SEO जांचा जा रहा है...",
    "audit.step.menu": "ऑनलाइन मेन्यू स्कैन हो रहा है...",
    "audit.step.visibility": "Google visibility चेक हो रही है...",
    "audit.step.report": "रिपोर्ट बन रही है...",
    "audit.category.mobile": "मोबाइल ऑप्टिमाइजेशन",
    "audit.category.speed": "पेज स्पीड",
    "audit.category.seo": "SEO",
    "audit.category.menu": "ऑनलाइन मेन्यू",
    "audit.category.visibility": "Google visibility",
    "audit.issue.single": "समस्या",
    "audit.issue.plural": "समस्याएं",
    "cta.titlePrefix": "अपने रेस्टोरेंट को",
    "cta.titleHighlight": "आज ही ऑनलाइन लाएं",
    "cta.description":
      "फॉर्म भरें और फ्री consultation पाएं. हम आपके restaurant की digital needs समझकर best plan बताएंगे.",
    "cta.point.free": "फ्री consultation, कोई commitment नहीं",
    "cta.point.fast": "3-5 दिन में वेबसाइट तैयार",
    "cta.point.support": "Dedicated support manager",
    "cta.point.guarantee": "100% satisfaction guarantee",
    "cta.formTitle": "फ्री कंसल्टेशन पाएं",
    "cta.formSubtitle": "हमारी team 24 घंटे के अंदर call करेगी",
    "cta.placeholder.restaurant": "रेस्टोरेंट का नाम *",
    "cta.placeholder.owner": "ओनर का नाम *",
    "cta.placeholder.phone": "फोन नंबर *",
    "cta.placeholder.city": "शहर",
    "cta.submit": "फ्री कंसल्टेशन पाएं",
    "cta.submitting": "सबमिट हो रहा है...",
    "cta.footer": "कोई cost नहीं. कोई commitment नहीं. सिर्फ एक call.",
    "owner.login.title": "ओनर डैशबोर्ड",
    "owner.login.welcome": "वापस स्वागत है",
    "owner.login.create": "अकाउंट बनाएं",
    "owner.login.fullName": "पूरा नाम",
    "owner.login.email": "ईमेल",
    "owner.login.password": "पासवर्ड",
    "owner.login.wait": "कृपया इंतज़ार करें...",
    "owner.login.signUp": "साइन अप",
    "owner.login.login": "लॉगिन",
    "owner.login.haveAccount": "क्या आपका अकाउंट पहले से है?",
    "owner.login.noAccount": "क्या आपका अकाउंट नहीं है?",
    "owner.orders": "ऑर्डर्स",
    "owner.billing": "बिलिंग",
    "owner.analytics": "एनालिटिक्स",
    "owner.menu": "मेन्यू",
    "owner.kitchen": "किचन",
    "owner.inventory": "इन्वेंटरी",
    "owner.tables": "टेबल्स और QR",
    "owner.rooms": "रूम्स और QR",
    "owner.expenses": "खर्चे",
    "owner.customers": "कस्टमर्स",
    "owner.staff": "स्टाफ",
    "owner.chain": "चेन",
    "owner.settings": "सेटिंग्स",
    "owner.install": "ऐप इंस्टॉल करें",
    "owner.support.whatsapp": "व्हाट्सऐप सपोर्ट",
    "owner.logout": "लॉगआउट",
    "dashboard.title": "ऑर्डर्स",
    "dashboard.tab.active": "एक्टिव",
    "dashboard.tab.new": "नया",
    "dashboard.tab.accepted": "स्वीकृत",
    "dashboard.tab.preparing": "तैयार हो रहा",
    "dashboard.tab.ready": "तैयार",
    "dashboard.tab.all": "सभी",
    "dashboard.ordersUnavailable": "ऑर्डर्स उपलब्ध नहीं हैं",
    "dashboard.ordersUnavailableHint": "आपका अकाउंट अभी किसी restaurant owner से linked नहीं है.",
    "dashboard.noOrders": "कोई ऑर्डर नहीं मिला",
    "dashboard.noOrdersHint": "ऑर्डर्स यहां real-time में दिखेंगे",
    "dashboard.table": "टेबल",
    "dashboard.justNow": "अभी",
    "dashboard.minutesAgo": "मि पहले",
    "dashboard.hoursAgo": "घं",
    "dashboard.mark": "मार्क करें",
    "dashboard.status.new": "नया",
    "dashboard.status.accepted": "स्वीकृत",
    "dashboard.status.preparing": "तैयार हो रहा",
    "dashboard.status.ready": "तैयार",
    "dashboard.status.served": "सर्व किया गया",
    "dashboard.status.cancelled": "रद्द",
    "expenses.title": "खर्चे और रिपोर्ट्स",
    "expenses.export": "CSV एक्सपोर्ट",
    "expenses.add": "खर्च जोड़ें",
    "expenses.unavailable": "खर्चे उपलब्ध नहीं हैं",
    "expenses.unavailableHint": "आपका अकाउंट अभी किसी restaurant owner से linked नहीं है.",
    "expenses.revenue": "रेवेन्यू",
    "expenses.expenses": "खर्चे",
    "expenses.netProfit": "नेट प्रॉफिट",
    "expenses.inventoryValue": "इन्वेंटरी वैल्यू",
    "expenses.profitMargin": "प्रॉफिट मार्जिन",
    "expenses.all": "सभी खर्चे",
    "expenses.none": "इस महीने कोई खर्च रिकॉर्ड नहीं है",
    "expenses.noneHint": "अपने costs track करने के लिए खर्च जोड़ें",
    "expenses.edit": "खर्च एडिट करें",
    "expenses.addDialog": "खर्च जोड़ें",
    "expenses.category": "कैटेगरी",
    "expenses.amount": "राशि (INR)",
    "expenses.pickDate": "तारीख चुनें",
    "expenses.paymentMethod": "पेमेंट मेथड",
    "expenses.notes": "नोट्स (optional)",
    "expenses.save": "खर्च सेव करें",
    "expenses.saved": "खर्च सेव हो गया",
    "expenses.deleted": "खर्च हटा दिया गया",
    "expenses.noData": "एक्सपोर्ट के लिए डेटा नहीं है",
    "settings.title": "रेस्टोरेंट सेटिंग्स",
    "settings.restaurantInfo": "रेस्टोरेंट जानकारी",
    "settings.logo": "लोगो",
    "settings.upload": "अपलोड",
    "settings.uploading": "अपलोड हो रहा...",
    "settings.change": "बदलिए",
    "settings.restaurantName": "रेस्टोरेंट नाम",
    "settings.phone": "फोन नंबर",
    "settings.timing": "टाइमिंग",
    "settings.opensAt": "खुलता है",
    "settings.closesAt": "बंद होता है",
    "settings.gstLocation": "GST और लोकेशन",
    "settings.gstNumber": "GST नंबर",
    "settings.gstPercentage": "GST प्रतिशत (%)",
    "settings.address": "पता",
    "settings.autoDetect": "लोकेशन ऑटो-डिटेक्ट करें",
    "settings.detecting": "डिटेक्ट हो रहा...",
    "settings.orderDiameter": "ऑर्डर डायमीटर (GPS Verification)",
    "settings.orderDiameterHint": "टेबल/रूम से ऑर्डर करने के लिए customers इस distance zone के अंदर होने चाहिए",
    "settings.payment": "पेमेंट",
    "settings.upi": "UPI ID",
    "settings.save": "सेटिंग्स सेव करें",
    "settings.saving": "सेव हो रहा...",
    "settings.logoUploaded": "लोगो अपलोड हो गया!",
    "settings.logoUploadFailed": "लोगो अपलोड फेल हुआ",
    "settings.logoRemoved": "लोगो हटा दिया गया",
    "settings.logoRemoveFailed": "लोगो हटाना फेल हुआ",
    "settings.savedSuccess": "सेटिंग्स सेव हो गईं!",
    "settings.saveFailed": "सेव नहीं हो पाया",
    "settings.gpsUnsupported": "इस device पर GPS supported नहीं है",
    "settings.locationDetected": "लोकेशन मिल गई!",
    "settings.fetchAddressFailed": "पता fetch नहीं हो पाया",
    "settings.locationDenied": "लोकेशन access deny हो गया",
    "settings.locationFailed": "लोकेशन detect नहीं हो पाई",
    "customer.tableOccupied": "अभी occupied है. कृपया staff से contact करें या दूसरा table QR scan करें.",
  },
};

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window === "undefined") return "en";
    const saved = window.localStorage.getItem(STORAGE_KEY);
    return saved === "hi" ? "hi" : "en";
  });

  useEffect(() => {
    window.localStorage.setItem(STORAGE_KEY, language);
    document.documentElement.lang = language === "hi" ? "hi" : "en";
  }, [language]);

  const value = useMemo<LanguageContextValue>(() => {
    const t = (key: string, fallback?: string) =>
      translations[language][key] || fallback || translations.en[key] || key;

    return {
      language,
      setLanguage: setLanguageState,
      toggleLanguage: () => setLanguageState((current) => (current === "en" ? "hi" : "en")),
      t,
    };
  }, [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
};
