-- Legacy placeholder migration.
-- The original broad public profile policy from this migration has been
-- superseded by later hardening migrations:
--   20260401014500_limit_public_profile_access.sql
--   20260402000000_finalize_public_rls_overrides.sql
-- Keeping this migration as a no-op prevents historical version mismatches
-- from reintroducing insecure public-read behavior when environments are repaired.
